spring:
  data:
    rest:
      base-path: /api
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/movierecom"
    username: movierecom
    password: taHR41yl234

logging:
  file:
    name: logs/app.log
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    
jwt:
  secret: jYxtu51yl234
  validity: 18000
  
app:
  url:
    auth: /api/user/auth
